# Generated by Django 5.1.7 on 2025-04-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restpractice', '0005_alter_authuser_email_alter_authuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
