# Generated by Django 5.1.7 on 2025-04-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restpractice', '0006_alter_authuser_first_name_alter_authuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='otp_failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authuser',
            name='otp_last_requested',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
